#!/usr/bin/env python3
"""
Weekly Newsletter Generator for GitHub Actions
Searches Tavily for AI news, tech news, and formats into a newsletter.
"""

import os
import json
import requests
from datetime import datetime, timedelta

TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY")
TAVILY_SEARCH_URL = "https://api.tavily.com/search"

NEWSLETTER_SECTIONS = [
    {"title": "🤖 AI & Machine Learning", "queries": ["biggest AI news this week", "new AI models released this week"]},
    {"title": "💻 Software Development", "queries": ["programming developer news this week", "new frameworks libraries released"]},
    {"title": "☁️ Cloud & Infrastructure", "queries": ["AWS Azure Google Cloud news this week", "DevOps Kubernetes updates"]},
    {"title": "🚀 Startups & Tech Industry", "queries": ["tech startup funding news India", "tech industry news this week"]},
    {"title": "📱 Products & Gadgets", "queries": ["new tech products launched this week", "smartphone gadget reviews trending"]},
    {"title": "🎓 Learning & Career", "queries": ["tech career trends 2025", "free online courses trending tech"]}
]


def search_tavily(query, max_results=5):
    if not TAVILY_API_KEY:
        return {"query": query, "answer": "API key not configured", "results": []}
    payload = {
        "api_key": TAVILY_API_KEY,
        "query": query,
        "search_depth": "advanced",
        "max_results": max_results,
        "include_answer": True
    }
    try:
        response = requests.post(TAVILY_SEARCH_URL, json=payload, timeout=30)
        response.raise_for_status()
        return response.json()
    except Exception as e:
        print(f"  Error: {e}")
        return {"query": query, "answer": "", "results": []}


def generate_section(section_config):
    print(f"  📝 {section_config['title']}")
    all_items = []
    summary = ""
    for query in section_config["queries"]:
        result = search_tavily(query)
        if result.get("answer"):
            summary = result["answer"]
        for item in result.get("results", []):
            all_items.append({
                "title": item.get("title", "Untitled"),
                "url": item.get("url", ""),
                "snippet": item.get("content", "")[:200],
                "score": item.get("score", 0)
            })
    seen_urls = set()
    unique_items = []
    for item in sorted(all_items, key=lambda x: x["score"], reverse=True):
        if item["url"] not in seen_urls:
            seen_urls.add(item["url"])
            unique_items.append(item)
    return {"title": section_config["title"], "summary": summary, "items": unique_items[:5]}


def main():
    today = datetime.utcnow().strftime("%Y-%m-%d")
    print(f"📰 Generating weekly newsletter for {today}")
    os.makedirs("newsletters", exist_ok=True)

    sections = []
    for section_config in NEWSLETTER_SECTIONS:
        sections.append(generate_section(section_config))

    week_start = (datetime.utcnow() - timedelta(days=7)).strftime("%B %d")
    week_end = datetime.utcnow().strftime("%B %d, %Y")

    md_file = f"newsletters/{today}_newsletter.md"
    with open(md_file, "w") as f:
        f.write(f"# 📰 Weekly Tech & AI Newsletter\n\n")
        f.write(f"**Week of {week_start} - {week_end}**\n\n---\n\n")
        for section in sections:
            f.write(f"## {section['title']}\n\n")
            if section["summary"]:
                f.write(f"> {section['summary']}\n\n")
            for i, item in enumerate(section["items"], 1):
                f.write(f"### {i}. [{item['title']}]({item['url']})\n\n")
                if item["snippet"]:
                    f.write(f"{item['snippet']}...\n\n")
            f.write("---\n\n")
        f.write("\n*Generated by [ai-tools](https://github.com/amrendramishra/ai-tools) automation*\n")

    json_file = f"newsletters/{today}_newsletter.json"
    with open(json_file, "w") as f:
        json.dump({"date": today, "generated_at": datetime.utcnow().isoformat(), "sections": sections}, f, indent=2)

    with open("newsletters/latest.json", "w") as f:
        json.dump({"date": today, "markdown": md_file, "json": json_file}, f, indent=2)

    print(f"\n✅ Newsletter generated: {md_file}")


if __name__ == "__main__":
    main()
