#!/usr/bin/env python3
"""
Notification Helper for GitHub Actions
Sends notifications via Telegram or creates GitHub issues as fallback.
"""

import os
import json
import requests
from datetime import datetime

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")
WORKFLOW_NAME = os.environ.get("WORKFLOW_NAME", "Unknown")
WORKFLOW_STATUS = os.environ.get("WORKFLOW_STATUS", "unknown")
WORKFLOW_URL = os.environ.get("WORKFLOW_URL", "")
CUSTOM_MESSAGE = os.environ.get("CUSTOM_MESSAGE", "")
REPO_NAME = os.environ.get("REPO_NAME", "amrendramishra/ai-tools")


def send_telegram(message):
    """Send notification via Telegram bot."""
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        print("  Telegram not configured, skipping...")
        return False
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "Markdown"}
    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            print("  ✅ Telegram notification sent!")
            return True
        else:
            print(f"  ❌ Telegram error: {response.status_code}")
    except Exception as e:
        print(f"  ❌ Telegram failed: {e}")
    return False


def create_github_issue(title, body):
    """Create a GitHub issue as notification fallback."""
    if not GITHUB_TOKEN:
        print("  No GITHUB_TOKEN, cannot create issue")
        return False
    url = f"https://api.github.com/repos/{REPO_NAME}/issues"
    headers = {"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    payload = {"title": title, "body": body, "labels": ["automation", "daily-digest"]}
    try:
        response = requests.post(url, json=payload, headers=headers, timeout=10)
        if response.status_code == 201:
            issue_url = response.json().get("html_url", "")
            print(f"  ✅ GitHub issue created: {issue_url}")
            return True
        else:
            print(f"  ❌ Issue creation failed: {response.status_code}")
    except Exception as e:
        print(f"  ❌ Issue creation failed: {e}")
    return False


def main():
    today = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    status_emoji = "✅" if WORKFLOW_STATUS == "success" else "❌" if WORKFLOW_STATUS == "failure" else "ℹ️"

    message = f"{status_emoji} *Workflow Notification*\n\n"
    message += f"*Workflow:* {WORKFLOW_NAME}\n"
    message += f"*Status:* {WORKFLOW_STATUS}\n"
    message += f"*Time:* {today}\n"
    if WORKFLOW_URL:
        message += f"*Details:* {WORKFLOW_URL}\n"
    if CUSTOM_MESSAGE:
        message += f"\n*Message:* {CUSTOM_MESSAGE}\n"

    print(f"🔔 Sending notification for: {WORKFLOW_NAME} ({WORKFLOW_STATUS})")

    # Try Telegram first
    sent = send_telegram(message)

    # Fallback to GitHub issue
    if not sent:
        title = f"{status_emoji} [{WORKFLOW_NAME}] {WORKFLOW_STATUS} - {datetime.utcnow().strftime('%Y-%m-%d')}"
        body = f"## Workflow Run Notification\n\n"
        body += f"- **Workflow:** {WORKFLOW_NAME}\n"
        body += f"- **Status:** {WORKFLOW_STATUS}\n"
        body += f"- **Time:** {today}\n"
        if WORKFLOW_URL:
            body += f"- **Run URL:** {WORKFLOW_URL}\n"
        if CUSTOM_MESSAGE:
            body += f"\n### Message\n{CUSTOM_MESSAGE}\n"
        body += f"\n---\n*Auto-generated by ai-tools notification system*"
        create_github_issue(title, body)

    print("🔔 Notification process complete.")


if __name__ == "__main__":
    main()
